### ISSUE TITLE
run SAAB_PLUS_DIAG error

### ISSUE THREAD

**Issue by RyanYip-Kat** [kovaltsuk1/saab_plus#2]
I got error when I run SAAB_PLUS_DIAG

Traceback (most recent call last):
  File "/home/ye/anaconda3/envs/BioAlignment/bin/SAAB_PLUS_DIAG", line 33, in <module>
    main()
  File "/home/ye/anaconda3/envs/BioAlignment/bin/SAAB_PLUS_DIAG", line 21, in main
    diagnostics()
  File "/home/ye/anaconda3/envs/BioAlignment/lib/python2.7/site-packages/saab_plus/run_diagnostics.py", line 25, in __call__
    self.check_anarci()
  File "/home/ye/anaconda3/envs/BioAlignment/lib/python2.7/site-packages/saab_plus/run_diagnostics.py", line 36, in check_anarci
    from anarci import run_anarci
  File "/home/ye/anaconda3/envs/BioAlignment/lib/python2.7/site-packages/anarci/__init__.py", line 3, in <module>
    from .anarci import *
  File "/home/ye/anaconda3/envs/BioAlignment/lib/python2.7/site-packages/anarci/anarci.py", line 123
    print(">%s"%name, file=f)
                          ^
SyntaxError: invalid syntax

**Comment by Liripo** [comment]
I also encountered this error, it looks like python3 syntax, I don't know how to solve it

**Comment by LiCanhui-Huyi** [comment]
Hello, I don't know if the above two have found a solution. But maybe my method can help later generations. At first, I encountered the same problem. I tried to search for "anarci" on my Linux. Then I found that there is also a folder named "anarci" in a dependency package "scalop" of saabplus. In "scale/anarci", "anarci. py" uses "f.write (">% s  n "% name)" instead of "print (">% s "% name, file=f)". So I changed the name of the original "narci" folder, and then copied "narci" from "scalop" to the package folder of Python 2, and then I could run SAAB_ PLUS_ DIAG.

**Comment by LiCanhui-Huyi** [comment]
The method mentioned above can run "DIAG", but there is another problem that I cannot solve when running "SAAB_PLUS". After trying for a long time, I chose to give up, and then I noticed that there was an image of saab plus in the docker. You can get it by running "docker pull ursuegen/saab_plus: 1.1.0". Of course, you can create a container directly on the docker to run saabplus, but I try to copy some files from the docker to my Linux to run locally. There is an anarci-1.3. tar, which contains the setup.py file. You can use Python 2 to install it. But there was another problem that I couldn't solve during the installation process. So I finally chose to copy the folder of anarci to the local Python 2 package folder from the container's Python 2 package folder. Then I can run "SAAB_PLUS_DIAG" and "SAAB_PLUS" smoothly.

**Comment by Liripo** [comment]
@LiCanhui-Huyi You can use this docker images:  <https://hub.docker.com/r/ursueugen/saab_plus>

**Comment by LiCanhui-Huyi** [comment]
> @LiCanhui-Huyi You can use this docker images: https://hub.docker.com/r/ursueugen/saab_plus

I know this image. But I'm a novice. It's more controllable for me to run commands locally.
