### ISSUE TITLE
No output.txt

### ISSUE THREAD

**Issue by robbinxiaochen** [kovaltsuk1/saab_plus#4]
I have tried to run the example file in EXAMPLE using;
`SAAB_PLUS -f example_H.fa -n 20 -s human
`
**However, I got the error as:**
>SAAB_PLUS -f Light_chain.fasta -c L -n 20
      FILE: Light_chain.fasta
     CORES: 20
  ORGANISM: human
     CHAIN: L
OutputName: output.txt
 OutputDir: .
SAAB plus log is found in saab_plus.log
Diagnostics log is found in diagnostics.log

        Initiating anarci parsing

        anarci parsing is done

        Initiating SAAB plus
gzip: output.txt: No such file or directory
Traceback (most recent call last):
  File "/home/lvxiaochen/anaconda3/envs/saab_plus/bin/SAAB_PLUS", line 255, in <module>
    STUDY.convert_fasta_to_frame().run()
  File "/home/lvxiaochen/anaconda3/envs/saab_plus/bin/SAAB_PLUS", line 178, in run
    saab_instance.initiate_SAAB()
  File "/home/lvxiaochen/.local/lib/python2.7/site-packages/saab_plus/RunSAAB.py", line 138, in initiate_SAAB
    os.rename("{0}.gz".format( self.output_name ), os.path.join( self.output_dir,"{0}.gz".format( self.output_name )))
OSError: [Errno 2] No such file or directory

**And the saab_plus.log is like:**
2021-03-04 16:42:04 INFO                Initiating structural annotation pipeline
2021-03-04 16:42:04 INFO              FILE: vloupe_clonotype1_consensus_2_reference_aa.fasta
2021-03-04 16:42:04 INFO             CORES: 20
2021-03-04 16:42:04 INFO          ORGANISM: human
2021-03-04 16:42:04 INFO             CHAIN: H
2021-03-04 16:42:04 INFO        OutputName: output.txt
2021-03-04 16:42:04 INFO         OutputDir: .
2021-03-04 16:42:04 INFO        Writing DIAGNOSTICS log

2021-03-04 16:42:04 INFO  Successfully imported: anarci
2021-03-04 16:42:04 INFO  Successfully imported: anarci germlines
2021-03-04 16:42:04 INFO  Successfully imported: anarci Accept
2021-03-04 16:42:04 INFO  Successfully imported: scalop
2021-03-04 16:42:04 INFO  Successfully imported: scalop assing
2021-03-04 16:42:04 INFO  Successfully imported: FREAD
2021-03-04 16:42:04 INFO  Successfully imported: FREAD ESS table
2021-03-04 16:42:04 INFO  Successfully imported: prosci module
2021-03-04 16:42:04 INFO  Successfully imported: Common module
2021-03-04 16:42:04 INFO   PDB template info file for H3 loop is located: OK
2021-03-04 16:42:04 INFO   PDB template info file for L3 loop is located: OK
2021-03-04 16:42:04 INFO   CDR-H3 cluster mapping file is located: OK
2021-03-04 16:42:04 INFO   CDR-L3 cluster mapping file is located: OK
2021-03-04 16:42:04 INFO   Directory with PDB frameworks for H3 loop is located: OK
2021-03-04 16:42:04 INFO   Directory with PDB frameworks for L3 loop is located: OK
2021-03-04 16:42:04 INFO  Directory with FREAD templates for H3 loop is located: OK
2021-03-04 16:42:04 INFO  Number of FREAD templates found: 3759
2021-03-04 16:42:04 INFO  Directory with FREAD templates for L3 loop is located: OK
2021-03-04 16:42:04 INFO  Number of FREAD templates found: 3606
2021-03-04 16:42:04 INFO  Imported pandas, Version 0.24.2
2021-03-04 16:42:04 INFO  Imported Bio, Version 1.70
2021-03-04 16:42:04 INFO        Starting ANARCI parsing

2021-03-04 16:42:04 INFO        checking version of anarci used
2021-03-04 16:42:04 INFO        ANARCI version 1.3 is used
2021-03-04 16:42:04 INFO        Total number of sequences: 35
2021-03-04 16:42:04 ERROR       ANARCI parsing failed to parse this chunk of sequences
2021-03-04 16:42:04 INFO        ANARCI parsing is finished
2021-03-04 16:42:04 INFO        Removing intermediate: vloupe_clonotype1_consensus_2_reference_aa.fasta_df.txt.gz
2021-03-04 16:42:04 INFO        Starting SAAB plus pipeline

2021-03-04 16:42:04 INFO        Loading Structures chunk: numbered_sabdab_imgt_fread.pkl
2021-03-04 16:42:05 INFO ################
2021-03-04 16:42:05 INFO        Numbered PDBs have been loaded into memory
2021-03-04 16:42:05 INFO Output Directory already exists

Could you please help me out? 
Thanks!

**Comment by krishnaroskin** [comment]
I'm having the same issue.

**Comment by LiCanhui-Huyi** [comment]
Hello, I want to ask you a question unrelated to this question. How do you match saab_ Plus and ANARCi? saab_ Plus is based on Python 2, while ANARCI is based on Python 3. When I run "SAAB_PLUS_DIAG", an error will occur:
File "/usr/lib/python2.7/site-packages/anarci/anarci.py", line 123
print(">%s"%name, file=f)
                                     ^
SyntaxError: invalid syntax
"File" is a parameter only available in Python 3's print. Obviously, Python 2 cannot run this command.
I want to know how you solve this problem?
Because I see this problem in issue, but no one provides a solution. So I came to ask you for advice. I'm sorry to bother you.
